-- AlterTable
ALTER TABLE "UdemyCourse" ADD COLUMN     "lastUpdated" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "monthlyMentionCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "yearlyMentionCount" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "mentionCount" SET DEFAULT 0;
